name: Update Pastebin Data

on:
  schedule:
    - cron: '*/10 * * * *' # Ejecuta este flujo de trabajo cada 10 minutos
  workflow_dispatch:

jobs:
  fetch-and-update-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Fetch Pastebin Data
      run: |
        curl https://pastebin.com/raw/2VRaccd2 > pastebin-data.txt
        echo "Contenido de pastebin-data.txt:"
        cat pastebin-data.txt
      
    - name: Commit and Push if Changed
      run: |
        git config --global user.name 'SaimusGaming'
        git config --global user.email 'contacto@Saimusgaming.es'
        git add pastebin-data.txt
        git diff --quiet || git commit -m "Update Pastebin data"
        git push
