name: Update Pastebin Data

on:
  schedule:
    - cron: '*/10 * * * *' # Ejecuta este flujo de trabajo cada 10 minutos
  workflow_dispatch:

jobs:
  fetch-and-update-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Fetch Pastebin Data
      run: |
        curl https://pastebin.com/raw/2VRaccd2 > data/pastebin-data.txt
        echo "Contenido de data/pastebin-data.txt:"
        cat data/pastebin-data.txt

   name: Update Pastebin Data

on:
  schedule:
    - cron: '*/10 * * * *' # Ejecuta este flujo de trabajo cada 10 minutos
  workflow_dispatch:

jobs:
  fetch-and-update-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Fetch Pastebin Data
      run: |
        curl https://pastebin.com/raw/2VRaccd2 > data/pastebin-data.txt
        echo "Contenido de data/pastebin-data.txt:"
        cat data/pastebin-data.txt

    name: Update Pastebin Data

on:
  schedule:
    - cron: '*/10 * * * *' # Ejecuta este flujo de trabajo cada 10 minutos
  workflow_dispatch:

jobs:
  fetch-and-update-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Fetch Pastebin Data
      run: |
        curl https://pastebin.com/raw/2VRaccd2 > data/pastebin-data.txt
        echo "Contenido de data/pastebin-data.txt:"
        cat data/pastebin-data.txt

- name: Commit and Push if Changed
  run: |
    git config --global user.name 'SaimusGaming'
    git config --global user.email 'contacto@Saimusgaming.es'
    git add data/pastebin-data.txt
    if git diff --staged --quiet; then
      echo "No hay cambios para cometer."
    else
      git commit -m "Update Pastebin data"
      git push
    fi
