name: Update Pastebin Data

on:
  schedule:
    - cron: '*/2 * * * *' # Ejecuta este flujo de trabajo cada 2 minutos para pruebas

jobs:
  fetch-pastebin-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Fetch Pastebin Data
      run: curl https://pastebin.com/raw/2VRaccd2 > pastebin-data.txt
      
    - name: Commit and Push if Changed
      run: |
        git config --global user.name 'SaimusGaming'
        git config --global user.email 'contacto@Saimusgaming.es'
        git add pastebin-data.txt
        git diff --quiet || git commit -am "Update Pastebin data"
        git push
